---
Title: Merge Template Commands
Code: <?delims new delimiters?>
<?output "filename.ext"?>
<!--
  This page was generated by Notenik 
  using the merge template named =$templatefilename$=
  and the data at =$parentfolder$=. 
-->
<?set global = 0?>
<?nextrec?>
<?include "filename.ext" ?>
<?ifchange ?>
<?if ?>
<?definegroup 1 “=$$="?>
<?ifendgroup 1 ?>
<?ifnewgroup 1 ?>
<?else?>
<?endif?>
<?loop?>

---
The Code field contains a complete set of Merge Template commands. 

